### ISSUE TITLE
Error in data preparation

### ISSUE THREAD

**Issue by vallettea** [adbrebs/taxi#10]
Hello, thanks for sharing your amazing work.
I'm trying to run your code but I can't figure out this error while i'm running `data/make_valid_cut.py test_times_0`:

```
/h/r/taxi # ❯❯❯ data/make_valid_cut.py test_times_0
Number of cuts: 5
Traceback (most recent call last):
  File "data/make_valid_cut.py", line 78, in <module>
    make_valid(sys.argv[1], outpath)
  File "data/make_valid_cut.py", line 24, in make_valid
    for line in taxi_it('train'):
  File "/home/root/taxi/data/hdf5.py", line 63, in taxi_it
    dataset = TaxiDataset(which_set, filename)
  File "/home/root/taxi/data/hdf5.py", line 16, in __init__
    super(TaxiDataset, self).__init__(self.data_path, (which_set,), **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/fuel/datasets/hdf5.py", line 146, in __init__
    "{}.".format(self.available_splits))
ValueError: '('train',)' split is not provided by this dataset. Available splits are (u'test', u'unique_taxi_id', u'train', u'stands', u'unique_origin_call').
```

**Comment by vallettea** [comment]
I think there is a typo  in line
https://github.com/adbrebs/taxi/blob/master/data/hdf5.py#L16

**Comment by vallettea** [comment]
Then during `data_analysis/cluster_arrival.py`:

```
/h/r/taxi # ❯❯❯ data_analysis/cluster_arrival.py
Traceback (most recent call last):
  File "data_analysis/cluster_arrival.py", line 13, in <module>
    from data.transformers import add_destination
  File "/home/root/taxi/data/transformers.py", line 9, in <module>
    from fuel.transformers import Batch, Mapping, SortMapping, Transformer, Unpack, FilterSources
ImportError: cannot import name FilterSources
```

although i'm running fuel with the proper commit

**Comment by vallettea** [comment]
Anyway `FilterSources` is not used so commenting line 25 in `data/transformers.py` solves the pb.

**Comment by ejls** [comment]
Alexandre Vallette notifications@github.com @2015-08-27T03:13:49-0700:

> Hello, thanks for sharing your amazing work.
> I'm trying to run your code but I can't figure out this error while i'm running `data/make_valid_cut.py test_times_0`:
> 
> ```
> /h/r/taxi # ❯❯❯ data/make_valid_cut.py test_times_0
> Number of cuts: 5
> Traceback (most recent call last):
>   File "data/make_valid_cut.py", line 78, in <module>
>     make_valid(sys.argv[1], outpath)
>   File "data/make_valid_cut.py", line 24, in make_valid
>     for line in taxi_it('train'):
>   File "/home/root/taxi/data/hdf5.py", line 63, in taxi_it
>     dataset = TaxiDataset(which_set, filename)
>   File "/home/root/taxi/data/hdf5.py", line 16, in __init__
>     super(TaxiDataset, self).__init__(self.data_path, (which_set,), **kwargs)
>   File "/usr/local/lib/python2.7/dist-packages/fuel/datasets/hdf5.py", line 146, in __init__
>     "{}.".format(self.available_splits))
> ValueError: '('train',)' split is not provided by this dataset. Available splits are (u'test', u'unique_taxi_id', u'train', u'stands', u'unique_origin_call').
> ```
> 
> IIRC a recent modification to Fuel makes it so that H5PYDataset which_set is a single value instead of a tuple.
> Which version of Fuel are you using ? You need to checkout commit ed725a7ff9f3d080ef882d4ae7e4373c4984f35a of Fuel, take a look at the README (something similar needs to be done for Blocks).
> Please let us know if this solve the problem.

## 

Étienne Simon

**Comment by ejls** [comment]
Alexandre Vallette notifications@github.com @2015-08-27T03:28:32-0700:

> Anyway `FilterSources` is not used so commenting line 25 in `data/transformers.py` solves the pb.

Select is used during the training though, so you need FilterSources.
Are you sure you have the correct version of Fuel ?
Maybe you have 2 versions installed, try to do something like : `python -c "import fuel; print fuel.__file__"`.

## 

Étienne Simon

**Comment by vallettea** [comment]
you are right about `FilterSources` needed in training:

```
/h/r/taxi # ❯❯❯ ./train.py dest_mlp_tgtcls_1_cswdtx_alexandre                                                                                                      ⏎
INFO:__main__:# Configuration: config.dest_mlp_tgtcls_1_cswdtx_alexandre
INFO:__main__:              batch_size 200
INFO:__main__:          dim_embeddings [('origin_call', 57106, 10), ('origin_stand', 64, 10), ('week_of_year', 52, 10), ('day_of_week', 7, 10), ('qhour_of_day', 96, 10), ('day_type', 3, 10), ('taxi_id', 448, 10)]
INFO:__main__:              dim_hidden [500]
INFO:__main__:               dim_input 90
INFO:__main__:              dim_output 3455
INFO:__main__:              max_splits 100
INFO:__main__:         n_begin_end_pts 5
Traceback (most recent call last):
  File "./train.py", line 58, in <module>
    train_stream = stream.train(req_vars)
  File "/home/root/taxi/model/mlp.py", line 74, in train
    valid = TaxiDataset(data.valid_set, data.valid_ds, sources=('trip_id',))
  File "/home/root/taxi/data/hdf5.py", line 16, in __init__
    super(TaxiDataset, self).__init__(self.data_path, (which_set), **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/fuel/datasets/hdf5.py", line 142, in __init__
    if which_set not in self.available_splits:
  File "/usr/local/lib/python2.7/dist-packages/fuel/datasets/hdf5.py", line 254, in available_splits
    return tuple(self.split_dict.keys())
  File "/usr/local/lib/python2.7/dist-packages/fuel/datasets/hdf5.py", line 238, in split_dict
    self._split_dict = H5PYDataset.parse_split_array(split_array)
  File "/usr/local/lib/python2.7/dist-packages/fuel/datasets/hdf5.py", line 222, in parse_split_array
    split, source, start, stop, available, comment = row
ValueError: too many values to unpack
```

coming back to the issue here is how i installed the dependencies:

```
RUN pip install Cython h5py
RUN pip install git+git://github.com/mila-udem/blocks.git@1e0aca9171611be4df404129d91a991354e67730 \
    -r https://raw.githubusercontent.com/mila-udem/blocks/stable/requirements.txt

# Install fuel
RUN pip install git+git://github.com/mila-udem/fuel.git@ed725a7ff9f3d080ef882d4ae7e4373c4984f35a
```

(i'm using docker)

**Comment by vallettea** [comment]
```
/h/r/taxi # ❯❯❯ python -c "import fuel; print fuel.__file__"                                                                                                       
/usr/local/lib/python2.7/dist-packages/fuel/__init__.pyc
```

**Comment by vallettea** [comment]
For some reason `pip install git+git://github.com/mila-udem/fuel.git@ed725a7ff9f3d080ef882d4ae7e4373c4984f35a` did not install the proper version of fuel.
once I was able to be sure I had the good version, all the previous errors disapeared.
Sorry I bothered you.

Here is a Dockerfile that make everything work.
Best

```
FROM ubuntu:latest

MAINTAINER Alexandre Vallette, alexandre.vallette@ants.builders

RUN apt-get update && apt-get install -y \
    vim \
    zsh \
    git \
    wget \
    screen 

RUN apt-get install -y software-properties-common python-software-properties
RUN apt-add-repository ppa:fish-shell/release-2
RUN apt-get update
RUN apt-get install -y fish
RUN chsh -s /usr/bin/fish

RUN apt-get update && apt-get install -y \
    libatlas3gf-base \
    libatlas-dev \
    python \
    python-dev \
    python-nose \
    python-pip \
    python-numpy \
    python-scipy \
    python-matplotlib \
    python-pandas 

RUN pip install ipython
RUN pip install -U scikit-learn 


# Install bleeding-edge Theano
RUN pip install --upgrade --no-deps git+git://github.com/Theano/Theano.git

# Install blocks
RUN apt-get update && apt-get install -y \
    build-essential \
    autoconf \
    libtool \
    pkg-config \
    libxml2-dev \
    libxslt1-dev

RUN apt-get install -y libhdf5-dev

RUN pip install Cython h5py
RUN pip install git+git://github.com/mila-udem/blocks.git@1e0aca9171611be4df404129d91a991354e67730 \
    -r https://raw.githubusercontent.com/mila-udem/blocks/stable/requirements.txt

# Install fuel
# RUN pip install git+git://github.com/mila-udem/fuel.git@ed725a7ff9f3d080ef882d4ae7e4373c4984f35a
RUN git clone https://github.com/adbrebs/taxi.git
RUN git checkout ed725a7ff9f3d080ef882d4ae7e4373c4984f35a
RUN python setup.py install

ENV PYTHONPATH "$PWD:$PYTHONPATH"

ENV TAXI_PATH taxi_data
```

**Comment by adbrebs** [comment]
Cool, let us know if you have any other issues!
